"""
Grounded Answer Generator Module
Synthesizes concise, source-grounded answers from retrieved vector context chunks
and passes responses through the Output Validation Guardrail.
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path

# Add backend directory to sys.path if running as standalone script
backend_dir = Path(__file__).resolve().parent.parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

from app.config import settings
from app.rag.validator import sanitize_or_fallback, validate_response
from app.utils.logger import get_logger

logger = get_logger("rag.generator")

SYSTEM_PROMPT_TEMPLATE = """You are the Groww Mutual Fund Facts-Only Assistant.
Your job is to answer the user query in MAXIMUM 1 to 2 sentences using ONLY the provided CONTEXT.
Do NOT add citation links, URLs, or date footers to your text—those will be attached programmatically.
If the answer cannot be verified from the CONTEXT, state exactly: "I couldn't verify this information from the available official sources."

CONTEXT:
{context_str}

QUERY:
{query}
"""

def synthesize_grounded_answer(query: str, retrieved_chunks: list[dict]) -> dict:
    """
    Synthesizes a grounded answer from retrieved vector context chunks.
    """
    if not retrieved_chunks:
        logger.warning("No retrieved context chunks available for generation.")
        return {
            "status": "fallback",
            "answer": settings.FALLBACK_RESPONSE_TEXT,
            "source_url": None,
            "is_valid": False
        }

    # Extract primary metadata from top chunk
    top_chunk = retrieved_chunks[0]
    top_meta = top_chunk.get("metadata", {})
    scheme_name = top_meta.get("scheme_name", "the scheme")
    source_url = top_meta.get("source_url", settings.ALLOWED_URLS[0])
    effective_date = top_meta.get("effective_date", datetime.now().strftime("%d %B %Y"))

    # Format context string
    context_blocks = []
    for c in retrieved_chunks:
        context_blocks.append(f"Fact Type: {c['metadata'].get('fact_type')}\nContent: {c['text']}")
    context_str = "\n---\n".join(context_blocks)

    statement = ""
    api_key = settings.GROQ_API_KEY or settings.OPENAI_API_KEY or os.getenv("GROQ_API_KEY", "") or os.getenv("OPENAI_API_KEY", "")

    # 1. Attempt LLM generation if API key is present
    if api_key:
        try:
            import openai
            if api_key.startswith("gsk_"):
                logger.info("Groq API key detected ('gsk_'). Directing request to Groq Cloud endpoint...")
                client = openai.OpenAI(api_key=api_key, base_url="https://api.groq.com/openai/v1")
                model_name = settings.GROQ_MODEL
            else:
                logger.info("OpenAI API key detected. Calling OpenAI API...")
                client = openai.OpenAI(api_key=api_key)
                model_name = os.getenv("LLM_MODEL_NAME", "gpt-3.5-turbo")

            prompt = SYSTEM_PROMPT_TEMPLATE.format(context_str=context_str, query=query)
            completion = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=100
            )
            raw_llm_text = completion.choices[0].message.content.strip()
            
            # Clean any accidental link or footer text generated by LLM
            clean_llm_text = re.sub(r'\[([^\]]+)\]\((https?://[^\)]+)\)', r'\1', raw_llm_text)
            clean_llm_text = re.sub(r'Source:.*', '', clean_llm_text, flags=re.IGNORECASE)
            clean_llm_text = re.sub(r'Last updated.*', '', clean_llm_text, flags=re.IGNORECASE)
            statement = clean_llm_text.strip()
            logger.info("LLM statement generated successfully.")
        except Exception as e:
            logger.error(f"LLM API generation error: {e}")
            statement = ""

    # 2. High-Precision Local Generator Fallback
    if not statement or statement == "I couldn't verify this information from the available official sources.":
        chunk_text = top_chunk["text"]
        clean_facts = []
        for line in chunk_text.split("\n"):
            if not line.startswith("Scheme Name:") and not line.startswith("Fact Category:") and not line.startswith("Source:"):
                clean_facts.append(line.strip())
        main_fact = " ".join(clean_facts).strip() if clean_facts else chunk_text
        sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', main_fact) if s.strip()]
        statement = " ".join(sentences[:2]) if len(sentences) > 2 else main_fact

    # 3. Assemble standardized response with canonical citation & date footer
    raw_answer = (
        f"{statement}\n\n"
        f"Source: [{scheme_name}]({source_url})\n"
        f"Last updated from sources: {effective_date}"
    )

    # 4. Pass raw answer through Output Validation Guardrail
    is_valid, reason = validate_response(raw_answer, allowed_urls=settings.ALLOWED_URLS)
    final_answer = raw_answer if is_valid else settings.FALLBACK_RESPONSE_TEXT

    if not is_valid:
        logger.warning(f"Generated response failed validation guardrail: {reason}")
    else:
        logger.info("Generated response passed all 5 output validation guardrails successfully.")

    return {
        "status": "success" if is_valid else "fallback",
        "answer": final_answer,
        "source_url": source_url,
        "last_updated": effective_date,
        "is_valid": is_valid,
        "validation_reason": reason
    }

if __name__ == "__main__":
    from app.rag.retriever import retrieve_context
    ret = retrieve_context("What is the expense ratio of HDFC Small Cap Fund?", scheme_slug="hdfc-small-cap-fund-direct-growth")
    res = synthesize_grounded_answer("What is the expense ratio of HDFC Small Cap Fund?", ret["retrieved_chunks"])
    print("Synthesized Output:\n", res["answer"])
